services:
  app:
    image: danielcavalcante/minio-chunked-upload-download
    build:
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - 5000:5000
    networks:
      - minio_chunked_network
    environment:
      - MINIO_HOSTNAME=minio-server

  minio:
    image: minio/minio
    container_name: minio-server
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001" 
    volumes:
      - storage-data:/data
    healthcheck:
            test:
                ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
    networks:
      - minio_chunked_network

networks:
    minio_chunked_network:
        name: minio_chunked_network

volumes:
  storage-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${MINIO_TMP_FOLDER}
